# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('OId', models.CharField(max_length=1000)),
                ('LTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Image', models.CharField(max_length=10000)),
                ('Bot', models.CharField(max_length=10000)),
                ('Members', models.CharField(max_length=1000)),
                ('Desc', models.TextField()),
                ('Backers', models.ManyToManyField(to='polls.Backer')),
            ],
        ),
    ]
