# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
