# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180324_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Backers',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Backer'),
        ),
    ]
