# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190222_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Backers',
            field=models.ManyToManyField(blank=True, to='polls.Backer'),
        ),
    ]
